{
    "default": true,
    "MD013": false,      # https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013---line-length
    "MD025": false       # https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md025---multiple-top-level-headings-in-the-same-document
}
